### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by rdranch** [ClaudiuGeorgiu/RiskInDroid#10]
Got an error:
sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute when connecting to sqlite database with flask-sqlalchemy

when trying to access results.
Solved issue by upgrading Flask-SQLAlchemy since default version here is 2.4.1. Current (and working) is >= 2.5.0
pip3 install Flask-SQLAlchemy -U

**Comment by ClaudiuGeorgiu** [comment]
Fixed by d5df713ffd029972f3dac9c3b2b0382a26496e07.
