### ISSUE TITLE
How does RiskInDroid get the corresponding permission of method call through static analysis?

### ISSUE THREAD

**Issue by LeviAckermaner** [ClaudiuGeorgiu/RiskInDroid#11]

**Comment by LeviAckermaner** [comment]
How does RiskInDroid get API to permission mapping?

**Comment by ClaudiuGeorgiu** [comment]
Hi, sorry but that part is handled by [PermissionChecker.jar](https://github.com/ClaudiuGeorgiu/RiskInDroid/blob/master/app/PermissionChecker.jar) which is not open source.
