### ISSUE TITLE
How to Extract/ Download the results

### ISSUE THREAD

**Issue by RoshnikRahat** [ClaudiuGeorgiu/RiskInDroid#16]
I have the results on local hosts, now I just want to extract and download them (pdf, json anything will do), Is there any feature/command which enables me to do so?
pls help?

**Comment by ClaudiuGeorgiu** [comment]
Hi, the repository contains a compressed sqlite db with all the results [app/database/permission_db.7z](https://github.com/ClaudiuGeorgiu/RiskInDroid/blob/cb46effbc1a55085b34fb5d1e3c53a1ea596836f/app/database/permission_db.7z), after you extract the db from the 7z archive you can use a command like this to get the data `sqlite3 permission_db.db "SELECT * FROM apks"`.
