### ISSUE TITLE
The uploaded file is not valid

### ISSUE THREAD

**Issue by NeonLost** [ClaudiuGeorgiu/RiskInDroid#3]
Foreach apk. Test on mac and ubuntu.

**Comment by ClaudiuGeorgiu** [comment]
Hi, did you resolve the issue? Otherwise please provide more information about the issue (e.g. a sample `.apk` file you used, whether you are using the docker version or you are running it directly on your computer, etc.). Thank you.

**Comment by supremehj** [comment]
i opened it in window 10 terminal the app opened correctly but when ever I tried to upload any apk it says Bad request
There was an error during the request. Make sure to upload a valid application and retry.
![image](https://github.com/ClaudiuGeorgiu/RiskInDroid/assets/149232077/a76d47b2-5aea-409e-a63b-92f4e4e86963)
