### ISSUE TITLE
Why can't I use apk size above 10 MB

### ISSUE THREAD

**Issue by ahsan2010** [ClaudiuGeorgiu/RiskInDroid#6]
Thank you for the tool. This tool is very good. 
However, I have noticed that the tool can not handle apk file size more than 10 MB. I am not sure why this tool can not handle more than 10 MB. Is there any way I can analyze apk size greater than 10 MB?

**Comment by ClaudiuGeorgiu** [comment]
See issue #4, the limitation is for the online version only.
