### ISSUE TITLE
Can't train new models

### ISSUE THREAD

**Issue by Ari-Zhang** [ClaudiuGeorgiu/RiskInDroid#9]
Hi, I deleted the contents of "app/models/" and tried to train the models again. I re-upload a new apk to parse it, but the errors tell me that it is a "Bad request". I check the "app/models/" folder found it is created successfully but no models in it. Do you know how could I train the model successfully? I use RiskInDroid directly from the source code. My python version is 3.8.3

**Comment by Ari-Zhang** [comment]
I tried to train models by myself, I added `rsk1 = RiskInDroid() rsk1.train_classifiers()` behind Line#65 `application = create_app()` in app.py.
I run it and get an error "RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/."
I don't know if I find the error corretly? By the way I am using windows.

**Comment by ClaudiuGeorgiu** [comment]
Hi, I'm on Windows 10 and I'm using Python 3.8 too, but I can't replicate the error. I deleted the `app/models/` directory and then used [this application](https://github.com/dineshshetty/Android-InsecureBankv2/blob/master/InsecureBankv2.apk) to test everything, and the models were created again as expected. Does everything work if you use the models already included in this repository instead of trying to train them again?

**Comment by Ari-Zhang** [comment]
Okay, But I want to check the 10 trating methods as you mentioned in the paper. Could I ask what is your python version? Maybe it's because the version I guess. Thanks a lot!

**Comment by ClaudiuGeorgiu** [comment]
This is what I have currently installed:
```
(venv) C:\Users\Claudiu\Desktop\GitHub\RiskInDroid>python --version
Python 3.8.3

(venv) C:\Users\Claudiu\Desktop\GitHub\RiskInDroid>python -m pip freeze
atomicwrites==1.3.0
attrs==19.3.0
click==7.1.1
colorama==0.4.3
coverage==5.1
Flask==1.1.2
Flask-SQLAlchemy==2.4.1
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==0.14.1
MarkupSafe==1.1.1
more-itertools==8.2.0
numpy==1.18.2+mkl
packaging==20.3
pluggy==0.13.1
py==1.8.1
pyparsing==2.4.7
pytest==5.4.1
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
SQLAlchemy==1.3.16
tqdm==4.45.0
wcwidth==0.1.9
Werkzeug==1.0.1
```

**Comment by Ari-Zhang** [comment]
Thanks a lot! I use your packages version and it worked!
